### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by dishb** [lebao3105/texteditor#4]
The "Running" instructions say to run the following command: `pip install -r requirements.txt`. However, in the `main` branch, no such file is present.

**Comment by lebao3105** [comment]
It’s my fault. I have added, and removed `requirements.txt` so many times.

**Comment by dishb** [comment]
No problem :)

**Comment by lebao3105** [comment]
Here's what you need:
```
./libtextworker[tk]
cairosvg
```

Cairosvg is used for converting the app logo to .png - and it's optional.

For libtextworker, make sure you have run ```git submodule update --init --recursive```

**Comment by lebao3105** [comment]
And... the ```main``` branch should be updated days ago:\

**Comment by dishb** [comment]
Interesting... okay, thank you.

**Comment by lebao3105** [comment]
If you have any problem, just inform me. Thanks for testing the app!
