### ISSUE TITLE
Bug: unable to run program

### ISSUE THREAD

**Issue by dishb** [lebao3105/texteditor#6]
On macOS 12.6.7, with Python 3.11.4, pip 23.2:

I run the following:
```bash
pip3 install texteditor
python3 -m texteditor
```

I get the following error:
```
/Library/Frameworks/Python.framework/Versions/3.11/bin/python3: No module named texteditor.__main__; 'texteditor' is a package and cannot be directly executed
```

**Comment by lebao3105** [comment]
My texteditor is published to TestPypi, not Pypi.

Please use ```pip install -i https://test.pypi.org/simple/ texteditor``` instead.

**Comment by lebao3105** [comment]
Here it runs fine:
![image](https://github.com/lebao3105/texteditor/assets/77564176/d85f9324-03ba-4c90-a87b-95f2bb053f6b)

**Comment by dishb** [comment]
> My texteditor is published to TestPypi, not Pypi.
> 
> Please use `pip install -i https://test.pypi.org/simple/ texteditor` instead.

Oh whoops, thank you!

**Comment by lebao3105** [comment]
@dishb Btw I’m focusing on WIP versions of this project, so that’s okay if you want to ask me about version 1.4.

But don’t use code on ‘’’main’’’ branch now, wip/1.5 instead

**Comment by lebao3105** [comment]
> ```
> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3: No module named texteditor.__main__; 'texteditor' is a package and cannot be directly executed
> ```


That’s why I renamed my project lol
